config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  # Make sure to define POST route for increment_async
  post 'increment_async', to: 'home#increment_async', as: 'increment_async'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @message = "Dynamic"

    @posts = Post.all
  end

  def increment_async
    # Use IncrementCountJob instead of IncrementCountWorker
    IncrementCountJob.perform_async(params[:post_id])
    redirect_to root_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
Home Page:

<%= @message %>

<% @posts.each do |post| %>
  <h1> <%= post.title %> </h1>
  <h2> <%= post.author.name %> </h2>
  <p> <%= post.body %>

    <br>

  <p>

    <%#= link_to "Like", increment_async_path(post_id: post.id), method: :post %>

    <%= form_with url: increment_async_path(post_id: post.id), method: :post do %>
      <%= submit_tag "Like1" %>
    <% end %>

    Likes:
    <%= post.likes_count %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDockerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>